#!/usr/bin/env python3
"""
Build the main README.md by consolidating all category READMEs.
Run: python3 build_main_readme.py
"""

from pathlib import Path

REPO_DIR = Path(__file__).parent

CATS = {
    "ai-agents-llm": {
        "name": "🤖 AI AGENTS & LLM",
        "desc": "Multi-agent frameworks, agent orchestration, LLM fine-tuning and infrastructure.",
        "count": 127,
    },
    "rag-knowledge": {
        "name": "🧠 RAG & KNOWLEDGE BASE",
        "desc": "Retrieval-Augmented Generation, vector search, knowledge graphs and context engineering.",
        "count": 56,
    },
    "python-tools": {
        "name": "🐍 PYTHON TOOLS & DATA",
        "desc": "Python ecosystem, data processing, ML/AI libraries, Jupyter notebooks.",
        "count": 52,
    },
    "web-ui": {
        "name": "🌐 WEB & UI",
        "desc": "Next.js, React, TypeScript, browser automation, CSS/UI frameworks.",
        "count": 18,
    },
    "dev-infra": {
        "name": "⚙️  DEV INFRA & TOOLING",
        "desc": "CLI tools, GitHub Actions, Docker, Kubernetes, shell scripts, developer infrastructure.",
        "count": 22,
    },
    "rust-systems": {
        "name": "🔧 RUST & SYSTEMS",
        "desc": "Rust ecosystem, browser engines, database engines, performance tooling.",
        "count": 5,
    },
    "data-analytics": {
        "name": "📊 DATA & ANALYTICS",
        "desc": "Dashboards, data pipelines, BI tools, analytics and visualization.",
        "count": 4,
    },
    "cloud-deploy": {
        "name": "☁️  CLOUD & DEPLOY",
        "desc": "AWS, GCP, Azure, serverless, Kubernetes, infrastructure-as-code.",
        "count": 1,
    },
}

def parse_table(readme_path):
    """Parse a category README and return list of (n, repo_url, lang, stars, forks, desc)."""
    lines = readme_path.read_text().splitlines()
    repos = []
    for line in lines:
        if not line.startswith("| ") or line.startswith("|---|") or " # |" in line:
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < 6 or not parts[1].isdigit():
            continue
        n = int(parts[1])
        # repo is markdown link: [owner/repo](https://github.com/owner/repo)
        repo_md = parts[2]
        import re
        m = re.search(r'\[([^\]]+)\]\(https?://github\.com/([^)]+)\)', repo_md)
        if not m:
            continue
        full_name = m.group(2)
        lang = parts[3]
        stars = parts[4]
        forks = parts[5]
        desc = parts[6] if len(parts) > 6 else ""
        repos.append((n, full_name, lang, stars, forks, desc))
    return repos

def build_main_readme():
    total = sum(CATS["count"] for CATS in CATS.values())

    lines = [
        "# ⭐ STARZ",
        "",
        f"> Your **{total}** starred GitHub repositories, organized into **{len(CATS)}** categories.",
        '',
        '*"A library is a collection of adventures you haven\'t had yet."*',
        "",
        "---",
        "",
        "## 📂 Categories",
        "",
        "| # | Category | Repos |",
        "|---|----------|-------:|",
    ]

    for i, (slug, info) in enumerate(CATS.items(), 1):
        folder_link = f"[{info['name']}](./{slug})"
        lines.append(f"| {i} | {folder_link} | {info['count']} |")

    lines.extend(["", "---", ""])

    for slug, info in CATS.items():
        readme_path = REPO_DIR / slug / "README.md"
        if not readme_path.exists():
            continue

        repos = parse_table(readme_path)

        lines.extend([
            f"## {info['name']}",
            "",
            f"{info['desc']}",
            "",
            f"**{len(repos)} repos** · [Browse folder](./{slug}/) · [Back to top](#-starz)",
            "",
            "| # | Repository | Language | ⭐ | 🍴 | Description |",
            "|---|-----------|----------|-----:|-----:|------------|",
        ])

        for n, full_name, lang, stars, forks, desc in repos:
            lines.append(f"| {n} | [{full_name}](https://github.com/{full_name}) | {lang} | {stars} | {forks} | {desc} |")

        lines.extend(["", f"*[{info['name']}](./{slug}/) · [Back to top](#-starz)*", ""])

    lines.append("---")
    lines.append("")
    lines.append("*Maintained by [@saidrassai](https://github.com/saidrassai) · Auto-generated by [starz](https://github.com/saidrassai/starz)*")

    (REPO_DIR / "README.md").write_text("\n".join(lines) + "\n")
    print(f"✅ Built README.md with {total} repos across {len(CATS)} categories")

if __name__ == "__main__":
    build_main_readme()
