#!/usr/bin/env python3
"""
starz index builder — generates a token-efficient "wiki" layer over the
collected starred repos, with NO GitHub API calls (reads local READMEs only).

Outputs (written into the repo root):
  INDEX.md   — master index: category counts + one compact table (repo | stars | lang | category | desc),
               sorted by stars desc. Grep-friendly; read only when asked "what's in starz".
  TOPICS.md  — reverse index: topic -> repos. Use this for subject search ("grpo", "rag", "finance").

Run:  python3 build_index.py
Also auto-invoked at the end of sync_stars.py (guarded, never breaks sync).
"""

from pathlib import Path
import re

REPO_DIR = Path(__file__).parent

CATS = {
    "ai-agents-llm":  "🤖 AI Agents & LLM",
    "rag-knowledge":  "🧠 RAG & Knowledge",
    "python-tools":   "🐍 Python Tools & Data",
    "web-ui":         "🌐 Web & UI",
    "dev-infra":      "⚙️ Dev Infra & Tooling",
    "rust-systems":   "🔧 Rust & Systems",
    "data-analytics": "📊 Data & Analytics",
    "cloud-deploy":   "☁️ Cloud & Deploy",
}

def parse_repo_readme(path: Path, cat: str) -> dict:
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return None
    rec = {"cat": cat, "full_name": "", "desc": "", "lang": "—",
           "stars": 0, "forks": 0, "license": "—", "topics": []}
    # full_name from H1: "# ⭐ owner/repo"
    m = re.search(r"^#\s*⭐\s*([^\n]+)", text, re.M)
    if m:
        rec["full_name"] = m.group(1).strip()
    # description = first non-empty line after H1
    lines = text.splitlines()
    for i, ln in enumerate(lines):
        if ln.startswith("# ⭐") or ln.startswith("# "):
            # next non-empty, non-header line is the desc
            for j in range(i + 1, min(i + 6, len(lines))):
                if lines[j].strip() and not lines[j].startswith("#") and not lines[j].startswith("|"):
                    rec["desc"] = lines[j].strip()
                    break
            break
    # Quick Info table — value cells may be wrapped in **bold**
    for key, field in (("Language", "lang"), ("Stars", "stars"), ("Forks", "forks"), ("License", "license")):
        pat = r"\|\s*\*{0,2}" + re.escape(key) + r"\*{0,2}\s*\|\s*([^|]+?)\s*\|"
        mm = re.search(pat, text)
        if mm:
            val = mm.group(1).strip().strip("*")
            if field in ("stars", "forks"):
                try:
                    rec[field] = int(val.replace(",", "").replace("?", "0"))
                except ValueError:
                    rec[field] = 0
            else:
                rec[field] = val
    # Topics line: "## 🏷️ Topics\ntopic1, topic2, ..."
    mt = re.search(r"##\s*🏷️\s*Topics\s*\n(.+)", text)
    if mt:
        raw = mt.group(1).strip()
        if raw and raw.lower() != "no topics":
            rec["topics"] = [t.strip().lower() for t in raw.split(",") if t.strip()]
    return rec

def collect() -> list:
    recs = []
    for cat in CATS:
        d = REPO_DIR / cat
        if not d.is_dir():
            continue
        for sub in sorted(d.iterdir()):
            rmd = sub / "README.md"
            if sub.is_dir() and rmd.exists():
                rec = parse_repo_readme(rmd, cat)
                if rec and rec["full_name"]:
                    recs.append(rec)
    return recs

def build_index(recs: list):
    total = len(recs)
    by_cat = {c: 0 for c in CATS}
    for r in recs:
        by_cat[r["cat"]] += 1

    # ── INDEX.md ──
    L = []
    L.append("# ⭐ STARZ — Index\n")
    L.append(f"> {total} starred repositories across {len(CATS)} categories. "
             "Auto-generated by `build_index.py` (local, no API). "
             "Grep this file for subjects; read per-repo READMEs for detail.\n")
    L.append("*Maintained by [@saidrassai](https://github.com/saidrassai) · "
             "Companion to the daily-synced [starz](https://github.com/saidrassai/starz).*\n")
    L.append("---\n")
    L.append("## 📂 Categories\n")
    L.append("| # | Category | Count |")
    L.append("|---|----------|------:|")
    for i, (c, name) in enumerate(CATS.items(), 1):
        L.append(f"| {i} | {name} | {by_cat[c]} |")
    L.append("")
    L.append("## 🔎 All repositories (by stars)\n")
    L.append("| Repo | ⭐ | Lang | Category | Description |")
    L.append("|------|----:|------|----------|-------------|")
    for r in sorted(recs, key=lambda x: x["stars"], reverse=True):
        desc = r["desc"].replace("|", "\\|").replace("\n", " ")
        if len(desc) > 90:
            desc = desc[:87] + "..."
        L.append(f"| [{r['full_name']}](https://github.com/{r['full_name']}) | {r['stars']:,} "
                 f"| {r['lang']} | {CATS[r['cat']]} | {desc} |")
    L.append("")
    L.append("---\n")
    L.append("*Generated by `build_index.py` · paired with `TOPICS.md` (subject reverse-index).*")
    (REPO_DIR / "INDEX.md").write_text("\n".join(L) + "\n")

    # ── TOPICS.md (reverse index) ──
    topic_map = {}
    for r in recs:
        for t in r["topics"]:
            topic_map.setdefault(t, []).append(r)
    T = []
    T.append("# ⭐ STARZ — Topics (reverse index)\n")
    T.append(f"> {len(topic_map)} distinct topics across {total} repos. "
             "Grep this file to find repos by subject (e.g. `grpo`, `rag`, `finance`, `agent`).\n")
    T.append("---\n")
    T.append("| Topic | # Repos | Repos (top by stars) |")
    T.append("|-------|--------:|----------------------|")
    for t in sorted(topic_map, key=lambda x: (-len(topic_map[x]), x)):
        rs = sorted(topic_map[t], key=lambda x: x["stars"], reverse=True)
        top = ", ".join(f"[{r['full_name']}](https://github.com/{r['full_name']})"
                        for r in rs[:6])
        if len(rs) > 6:
            top += f", … (+{len(rs)-6})"
        T.append(f"| {t} | {len(rs)} | {top} |")
    T.append("")
    T.append("---\n")
    T.append("*Generated by `build_index.py`.*")
    (REPO_DIR / "TOPICS.md").write_text("\n".join(T) + "\n")

    return total, len(topic_map)

def main():
    recs = collect()
    total, ntopics = build_index(recs)
    print(f"✅ Indexed {total} repos → INDEX.md (master) + TOPICS.md ({ntopics} topics)")

if __name__ == "__main__":
    main()
